
livereload: true

# user config
domain: hazalates.io
url: https://hazalates.io
email: "hazalates8@gmail.com"
insta: "https://www.instagram.com/vuurinhetturks/"

permalink: /:title:output_ext

plugins:
 - jekyll-sitemap
 - jekyll-seo-tag

defaults:
- scope:
   path: ""
   type: "posts"
  values:
   layout: "post"
- scope:
   path: ""
  values:
   layout: "default"